name: Build
on:
  workflow_dispatch:
  repository_dispatch:
    types: [build-pre-rel]
permissions:
  contents: read
jobs:
  build:
    name: Build
    runs-on: windows-2025-vs2026
    steps:
      - name: Check out source code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Build release
        run: bun .\cmd\build.ts -release

      - name: Upload SumatraPDF installer
        uses: actions/upload-artifact@v4
        with:
          name: SumatraPDF-x64-installer
          path: out/rel64/SumatraPDF-*-64-install.exe
          if-no-files-found: error
